### ISSUE TITLE
无法保存设置

### ISSUE THREAD

**Issue by ManuZhu0728** [ChisBread/transmission_skip_patch#10]
系统为unraid，配置好后无法保存配置，tr中显示/config为只读，unraid终端中手动设置文件夹权限、变更UID和GID后，再次启动时，`setting.json`和`stats.json`又会变为`-rw------- root root`，无法保存😢不知道是unraid问题还是我配置错了

**Comment by ChisBread** [comment]
应该是特定平台问题，检查一下是否使用了正确的UID/GID

**Comment by ManuZhu0728** [comment]
> 应该是特定平台问题，检查一下是否使用了正确的UID/GID

我是第一次玩nas，设置了uid为1000对应自己建的用户，gid为100对应user。是不是得改成root/root对应的uid与pid才行呀😂

**Comment by ChisBread** [comment]
不，使用对应用户的UID:GID是合理的
检查是否使用了r10版本的镜像？按理说不应该出现这种情况

**Comment by ManuZhu0728** [comment]
> 不，使用对应用户的UID:GID是合理的 检查是否使用了r10版本的镜像？按理说不应该出现这种情况

是用的r10版本镜像。现在终端里查看倒是显示对应用户，不过只要重启容器，最后一张图里的三个框就会自己勾上

![image](https://user-images.githubusercontent.com/62131027/154413297-66551303-b77e-4d5c-9bf5-f2b53ee61122.png)

![image](https://user-images.githubusercontent.com/62131027/154413348-70bc6831-6673-4fff-985f-aea15a10b2ab.png)

![image](https://user-images.githubusercontent.com/62131027/154413444-2e741227-f45b-4e5b-b04e-0db9e7da7630.png)

![image](https://user-images.githubusercontent.com/62131027/154413597-a01f95a4-5131-4b85-b0e3-59bbd2fc5320.png)

![image](https://user-images.githubusercontent.com/62131027/154414052-23285337-ef58-4130-a4bb-9a551dcb3c10.png)

**Comment by ChisBread** [comment]
我猜测你停止容器使用的操作类似docker kill, 而非docker stop。而前者不会触发配置保存。
按照以下方法进行测试
1. 删除配置文件，重新启动容器，修改配置并保存
2. docker ps 找到对应容器的container id
3. docker stop ${ID}
3. 重启，观察配置是否保存

**Comment by ManuZhu0728** [comment]
> 我猜测你停止容器使用的操作类似docker kill, 而非docker stop。而前者不会触发配置保存。 按照以下方法进行测试
> 
> 1. 删除配置文件，重新启动容器，修改配置并保存
> 2. docker ps 找到对应容器的container id
> 3. docker stop ${ID}
> 4. 重启，观察配置是否保存

没有，还是一样的😢

**Comment by ChisBread** [comment]
那就奇怪了...等使用unraid的大佬来诊断一下吧

**Comment by ChisBread** [comment]
@lbcz-tian 
hello, 请尝试r12以后的版本, 理论上问题已经解决

**Comment by ManuZhu0728** [comment]
> @lbcz-tian hello, 请尝试r12以后的版本, 理论上问题已经解决

我使用latest标签试了下，还是无法保存设置额

**Comment by ChisBread** [comment]
尝试r12标签，或者删除latest镜像重新拉取，确保的确更新

**Comment by ManuZhu0728** [comment]
> 尝试r12标签，或者删除latest镜像重新拉取，确保的确更新

我重新用r12标签拉取了，还是无法在web-control里直接保存设置，但是可以直接编辑`settings.json`
