### ISSUE TITLE
之前装的是qnapclub上的tr， webui也是， 这要怎么升级成快检版？

### ISSUE THREAD

**Issue by cooltnt** [ChisBread/transmission_skip_patch#11]
如果下载大佬的qnap套件安装，原来装的配置是不是会被覆盖掉？ 如果单纯的升级，需要覆盖哪些文件？  是参照patchspk.sh里的逻辑，提取qpkg中的文件更新吗？

**Comment by ChisBread** [comment]
qnap做成了不同名的安装包，和官方版相互独立。
1.停止官方版套件
2.安装快检版
3.将官方版的设置目录（包含种子等信息，可在/opt/文件夹下寻找套件目录）拷贝到快检版套件目录下
4.检查种子迁移是否正确
5.删除官方版套件

**Comment by cooltnt** [comment]
感谢回复, 你说的方法, 其实就是重新安装了 

    实际上我下了你的代码编译了, 但是发现只替换几个可执行程序不行. 

    不过我是在我家威联通(arm)上又装了个ubuntu的docker版编译的, 估计还是环境上的差异. 

    不知道能不能在威联通上直接部署编译环境?  一直百度不到这方面资料




***@***.***
 
发件人： Bread
发送时间： 2022-02-16 21:36
收件人： ChisBread/transmission_skip_patch
抄送： cooltnt; Author
主题： Re: [ChisBread/transmission_skip_patch] 之前装的是qnapclub上的tr， webui也是， 这要怎么升级成快检版？ (Issue #11)
qnap做成了不同名的安装包，和官方版相互独立。
1.停止官方版套件
2.安装快检版
3.将官方版的设置目录（包含种子等信息，可在/opt/文件夹下寻找套件目录）拷贝到快检版套件目录下
4.检查种子迁移是否正确
5.删除官方版套件
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ChisBread** [comment]
重新编译，需要使用正确的toolchain(etc. gcc ...)，你可以在威联通官网找到
我使用了取巧的方式，将需要的环境打包到了qpkg中
可以试试使用/opt/TransmissionPT3下的相关文件（.sh ./bin ./etc ...)覆盖原版的文件。其中.sh文件负责处理套件的启动、停止，其余的为可执行文件以及其它依赖（如ca, webui, 默认配置等)
这理论上是可行的

**Comment by ChisBread** [comment]
对于非常规的使用（自编译，特殊方法安装），由于并非项目本身的问题，不做进一步跟进。

**Comment by cooltnt** [comment]
非常感谢!



***@***.***
 
发件人： Bread
发送时间： 2022-02-17 13:48
收件人： ChisBread/transmission_skip_patch
抄送： cooltnt; Author
主题： Re: [ChisBread/transmission_skip_patch] 之前装的是qnapclub上的tr， webui也是， 这要怎么升级成快检版？ (Issue #11)
重新编译，需要使用正确的toolchain(etc. gcc ...)，你可以在威联通官网找到
我使用了取巧的方式，将需要的环境打包到了qpkg中
可以试试使用/opt/TransmissionPT3下的相关文件（.sh ./bin ./etc ...)覆盖原版的文件。其中.sh文件负责处理套件的启动、停止，其余的为可执行文件以及其它依赖（如ca, webui, 默认配置等)
这理论上是可行的
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
