### ISSUE TITLE
请问如何看是否开启快速校验了呢？

### ISSUE THREAD

**Issue by foreverlong** [ChisBread/transmission_skip_patch#12]
我勾选了一个任务点那个获取更多peer后，没有提示，获取peer也还是灰色的？请问如何看是否开启快速校验了呢？

**Comment by ChisBread** [comment]
为什么要点获取更多peer？快速校验是默认开启的，文档中已经强调。
要验证快速校验是否生效，请重新校验一个种子观察速度，10GB/s左右是正常速度。
目前没有fork webui进行修改的计划，所以不会有可视化的状态显示。
