### ISSUE TITLE
win版本崩溃

### ISSUE THREAD

**Issue by chploin** [ChisBread/transmission_skip_patch#13]
目前发现小于100G的包都可以，大包200G左右及以上的 就会崩溃，看了下磁盘读写速度最大2W MB/s，什么原因呢，能不能优化呢？

**Comment by chploin** [comment]
用正常速度校验就没问题

**Comment by chploin** [comment]
![微信截图_20220326101947](https://user-images.githubusercontent.com/46960883/160221343-0e13f713-4287-4581-9220-7b6ed68cba05.png)

**Comment by ChisBread** [comment]
已知现象，暂时没有在Windows上进一步优化的计划。
