### ISSUE TITLE
R12无法打开

### ISSUE THREAD

**Issue by naoki66** [ChisBread/transmission_skip_patch#14]
2022-03-30 15:48:34	stdout	[2022-03-30 23:48:34.535] transmission-daemon Error loading config file -- exiting. (daemon.c:822)

**Comment by naoki66** [comment]
群辉docker无论是覆盖还是新建，一直报错
[2022-03-31 13:30:48.968] transmission-daemon Error loading config file -- exiti
ng. (daemon.c:822)  

无法打开web页面，ERR_EMPTY_RESPONSE

**Comment by ChisBread** [comment]
1. 补充详细的信息
系统/平台； 如 群晖DSM6.2.3
启动命令；
配置文件
2. 检查权限设置是否正确
尝试使用PUID=0, PGID=0启动

**Comment by naoki66** [comment]
群晖7.0.1 42218+docker 20.10.3-1239
导出配置如下
{
   "CapAdd" : null,
   "CapDrop" : null,
   "cmd" : "",
   "cpu_priority" : 50,
   "enable_publish_all_ports" : false,
   "enable_restart_policy" : true,
   "enabled" : true,
   "entrypoint_default" : "/init",
   "env_variables" : [
      {
         "key" : "PATH",
         "value" : "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      },
      {
         "key" : "PS1",
         "value" : "$(whoami)@$(hostname):$(pwd)\\$ "
      },
      {
         "key" : "HOME",
         "value" : "/root"
      },
      {
         "key" : "TERM",
         "value" : "xterm"
      },
      {
         "key" : "RPCPORT",
         "value" : "9091"
      },
      {
         "key" : "TRANSMISSION_WEB_HOME",
         "value" : "/transmission-web-control/"
      },
      {
         "key" : "TZ",
         "value" : "Asia/Shanghai"
      }
   ],
   "exporting" : false,
   "id" : "325bc32aafdb105cf5ac13101f44be1e05c493fecd7ef62fcded21207b3ec865",
   "image" : "chisbread/transmission:latest",
   "is_ddsm" : false,
   "is_package" : false,
   "links" : [],
   "memory_limit" : 6291456000,
   "memory_limit_slider" : 6000,
   "name" : "chisbread-dc",
   "network" : [
      {
         "driver" : "bridge",
         "name" : "bridge"
      }
   ],
   "network_mode" : "bridge",
   "port_bindings" : [
      {
         "container_port" : 51413,
         "host_port" : 51413,
         "type" : "tcp"
      },
      {
         "container_port" : 51413,
         "host_port" : 51413,
         "type" : "udp"
      },
      {
         "container_port" : 9091,
         "host_port" : 9091,
         "type" : "tcp"
      }
   ],
   "privileged" : false,
   "shortcut" : {
      "enable_shortcut" : false,
      "enable_status_page" : false,
      "enable_web_page" : false,
      "web_page_url" : ""
   },
   "use_host_network" : false,
   "volume_bindings" : [
      {
         "host_volume_file" : "/docker/temp",
         "mount_point" : "/downloads",
         "type" : "rw"
      },
      {
         "host_volume_file" : "/RAID/Sysback/docker/transmission/watch",
         "mount_point" : "/watch",
         "type" : "rw"
      },
      {
         "host_volume_file" : "/RAID/Sysback/docker/transmission/config",
         "mount_point" : "/config",
         "type" : "rw"
      }
   ]
}

**Comment by naoki66** [comment]
应该是群晖权限问题，修改  
   - PUID=0
    - PGID=0
   同时打开docker高权限，执行没有问题了

**Comment by ChisBread** [comment]
好的
