### ISSUE TITLE
出现双份做种，很可能会被认为在作弊

### ISSUE THREAD

**Issue by ylqjgm** [ChisBread/transmission_skip_patch#17]
情况描述：
在最新版Docker中，我从qb转移种子到了tr，比如总计100个种子，然后又使用iyuu进行辅种，比如辅种有20个，那么就是120个，假设这120个种子里有20个馒头，20个天空，剩下的是其他站的，当我效验完成后，启动种子开始做种，此时有一定机率会出现我做种20个，但是在馒头、天空等等里出现了40个，仔细检查会发现都是同样的种子
同时有机率会出现红种，提示不能同时上传2个种子，如果此时将种子暂停再重新开始，又会有概率出现网站内三分种子做种，也就是60个

可以看图（我hd.ai这个站总的有40个种子）：
![1649731899312](https://user-images.githubusercontent.com/5463368/162870059-7dfaa0f5-4a13-406e-9e60-22dae4db80bb.jpg)

登录网站可以看到显示80个上传：
![1649731952375](https://user-images.githubusercontent.com/5463368/162870122-6c303217-aeb6-448e-a8d7-2a95c0b65345.jpg)

查看做种列表可以看到都是同种子两份做种：
![1649731975883](https://user-images.githubusercontent.com/5463368/162870180-69163cb5-3c1f-444e-8fbc-e835584c9160.jpg)

而检查自己的客户端，可以看到只有一个客户端在运行，而且就是自己目前在用的：
![1649732037710](https://user-images.githubusercontent.com/5463368/162870247-43b5c14a-0435-417b-99fb-5426e8c73f94.jpg)

**Comment by ChisBread** [comment]
首先感谢你详细的反馈，表达得很清晰
你不用担心，这种情况不会导致封号，也并非快检导致的"bug"，是BT/PT tracker实现的特性: "依赖announce"
正如你所见，种子反复重新做种时，不活跃的做种未从列表中消失
但一段时间过后，tracker会自动清理不活跃的种子，不用在意这种现象

**Comment by ylqjgm** [comment]
> 

非常感谢耐心回复，主要没理解原理，既然是特性的话，那就无事了，还吓得我把TR赶紧暂停

**Comment by ChisBread** [comment]
happy seeding!
