### ISSUE TITLE
watch进程占用高，没有监控种子需求的可不可以提供关闭选项？

### ISSUE THREAD

**Issue by QZBT** [ChisBread/transmission_skip_patch#18]
![Shell_20220413-173302-203](https://user-images.githubusercontent.com/48495382/163155964-000439dc-5c6d-437b-b2dc-1900392f9917.png)

经常性高占用

**Comment by ChisBread** [comment]
不知道你怎么得到watch占用高的结论的
transmission-daemon是tr本体，如果觉得占用高，可以限制容器资源
如果想关闭watch功能，可以在WebUI或settings.json中设置，自行查阅transmission官方文档

另外这个issue与本项目无关，所以关闭了
