### ISSUE TITLE
docker版本安装上连不上9091

### ISSUE THREAD

**Issue by MarsBaby9** [ChisBread/transmission_skip_patch#20]
使用docker-compose的默认配置，修改了路径和用户名密码， pull了docker版本，但是连不上9091请问是为什么呢？debian10，并且删除了防火墙。谢谢
CONTAINER ID   IMAGE                    COMMAND   CREATED        STATUS        PORTS                                                                                                                                     NAMES
b59a5fced915   chisbread/transmission   "/init"   14 hours ago   Up 13 hours   0.0.0.0:9091->9091/tcp, :::9091->9091/tcp, 0.0.0.0:51413->51413/tcp, :::51413->51413/tcp, 0.0.0.0:51413->51413/udp, :::51413->51413/udp   transmission

**Comment by ChisBread** [comment]
信息不足，尝试收集足够的信息，再重新提issue
