### ISSUE TITLE
开一贴感谢作者解决了我下载时cpu单核卡100%的难题

### ISSUE THREAD

**Issue by bg4vrg** [ChisBread/transmission_skip_patch#24]
硬件：
华为rh2288 v3 
Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz *2
内存378G
系统：truenas scale
使用自带的docker安装了最新版的linuxserver/transmission
问题：如果不下载仅仅保种上传，即使上传十几MB，cpu也很稳定的低占用率。当下载1个种子，下载速度即使2-3MB，服务器cpu单核也狂飙到100%（无论是truenas仪表盘还是命令行中top命令都是99%以上）
在张大妈看到这篇文章时https://post.smzdm.com/p/aenlnk0q/已经换了好多个低版本的docker镜像了，但问题老样子
即使在docker中把cpu限制在10%后，占用是低了，但是web访问就也变卡了，实际无法操作。

感谢作者的辛苦劳动，虽然现在解决了，但是可能是什么原因导致的呢？以前用黑群晖跑2.7x的tr时没有遇到这样情况，不知道是dockr版本的问题还是底层系统原因。

**Comment by ChisBread** [comment]
感谢反馈
单核100%的问题我没有复现过，猜测和编译方式、或编译参数有关。
我不清楚linuxserver/transmission如何编译。
chisbread/transmission使用了alpine发行版软件包内的工具链编译，编译优化开到了-O3，也许是某段高占用的代码被优化了，也可能是其它玄学原因
