### ISSUE TITLE
docker版的没有arm_v8的吗？

### ISSUE THREAD

**Issue by Hustle-Tung** [ChisBread/transmission_skip_patch#5]

**Comment by ChisBread** [comment]
因为没有设备可以测试，所以docker版本没有支持arm的计划。（也许我可以试试树莓派？）
实际上只要参考我的Dockerfile，就可以基于spk在arm环境里执行transmission-daemon

**Comment by ChisBread** [comment]
可以尝试镜像 chisbread/transmission:latest-armhf
如果有任何问题，在这个issue反馈即可

**Comment by ChisBread** [comment]
已测试可用
