### ISSUE TITLE
docker版的不能取消rpc登录验证嘛？

### ISSUE THREAD

**Issue by kangbeicai** [ChisBread/transmission_skip_patch#6]
我把rpc-authentication-required改成false重启就变回true了？
我不准备把端口转发出来，所以不想设置密码访问。而且tr的webui经常会卡， 加上密码体验很差。

**Comment by ChisBread** [comment]
可以的，只要把环境变量 USER 和 PASS 置为空，就会自动关闭auth
具体参考:
https://github.com/ChisBread/transmission_skip_patch/blob/master/start.sh
