### ISSUE TITLE
"2021-10-9的latest-armhf"无法加速且CPU占用持续增长卡死机器

### ISSUE THREAD

**Issue by Hustle-Tung** [ChisBread/transmission_skip_patch#8]
docker-armhf 版的
无论点几次"获取更多peer", 依然是2MB/s的校验速度，并且在校验到一二百MB的时候卡住不动，刷新web页面进不去，看CPU占用发现很高，删除本地resume文件重新添加并观察CPU占用发现是逐步升高，难道是一直在新开进程嘛，我无法使用，希望大佬可以解答一下

CPU占用：
transmission-daemon -g /config -c /watch -e /config/transmission.log -x /var/transmission.pid -f   |   89.57%

硬件：
N1小钢炮 (SoC: Amlogic S912)

docker命令：
#!/bin/sh

IMAGE_NAME=chisbread/transmission:latest-armhf

docker pull ${IMAGE_NAME} && \
docker run -d --name transmission300skip \
  -e USER=asd \
  -e PASS=asd \
  -e RPCPORT=9092 \
  -e PEERPORT=51215 \
  --restart unless-stopped \
  --network host \
  -p 9092:9092 \
  -p 51215:51215 \
  -p 51215:51215/udp \
  -v /var/lib/transmission:/config \
  -v /media/new:/downloads \
  -v /root:/watch \
  ${IMAGE_NAME}

**Comment by ChisBread** [comment]
感谢反馈
armhf的测试是在猫盘(Marvell ARMADA A3720)上进行的。因为不了解ARM架构，不确定是否同样兼容N1盒子。
因为手上没有N1盒子，所以我也只能猜测。

我注意到/watch目录是这样挂载的
```
-v /root:/watch
```
虽然没有仔细读过transmission关于目录监控的代码，但我猜测要实现watch功能需要进行文件扫描。
/root目录下是否有过多的文件？

**Comment by Hustle-Tung** [comment]
root目录下仅有14个文件，我用`linuxserver/transmission:arm64v8-3.00-r2-ls102`的docker没有出现问题，应该不是watch的问题

**Comment by ChisBread** [comment]
好的，那估计是兼容性问题了
我提供了armhf的Dockerfile，感兴趣的话可以看看。
其实就是解包群晖的spk再安装到基础镜像里，有能力的话可以自己选择对应架构的基础镜像和spk构建你的镜像。

**Comment by izatyazrai** [comment]
我用的n1 openwrt docker安装也是检验一半直接卡死退出，不太会这个希望大佬可以出一个N1的安装镜像，有些时候用久了还会卡崩docker

**Comment by Hustle-Tung** [comment]
额，没学过docker，不会构建镜像，希望大佬有机会的话搞一下

**Comment by ChisBread** [comment]
好的，等有N1的测试条件了就提上日程

**Comment by Hustle-Tung** [comment]
谢谢大佬

**Comment by ChisBread** [comment]
最近有N1正常使用的反馈，看起来镜像本身没有问题，不确定是启动参数还是系统导致的问题。

**Comment by Hustle-Tung** [comment]
我刚才又改了watch目录，还是开头那种情况，唉，从QB转TR校验个没完令人烦
