### ISSUE TITLE
希望将open-file-limit功能回归

### ISSUE THREAD

**Issue by cereushy** [ChisBread/transmission_skip_patch#9]
使用这个版本的，大多是pt用户吧。。。
我是典型的小水管+相对大的硬盘。
Tr在2.31以后就取消了同时读取文件的限制。
保种时，大量的上传因为带宽不够，只有几十k，然后硬盘狂响，实在没有效率。
现在只能将连接数设置成20，（我是公网所以连接性不错），大概会同时有12个左右的任务，每个几百K，再低就会出现一个任务上传完毕，没有新任务跟进，上传真空期。
需要下载时再把连接数调成70-100.
这样很麻烦。
我满带宽把前面的任务先传输完再回来继续下一个，要科学的多。
qb就可以限制同时上传的文件数。。。不知道为啥tr会取消。。。

**Comment by ChisBread** [comment]
增加新特性的成本太高啦，还需要魔改webui
因为时间关系，没有做新特性的计划

**Comment by cereushy** [comment]
好的，目前的快验真的帮了大忙，大佬哪天心情好了再考虑吧~
